import { type ComponentInstance } from "@/labs/types";

export const components: ComponentInstance[] = [
  { id: "bb", type: "long-breadboard" },
  {
    id: "psu",
    type: "dc-jack",
    mountedAt: { board: "bb", col: 1, row: "a" },
    terminals: [
      { board: "bb", rail: "vcc_top", col: 6 },
      { board: "bb", rail: "gnd_top", col: 6 },
    ],
  },
  {
    id: "nor_y0",
    type: "nor-gate",
    mountedAt: { board: "bb", col: 4, row: "e" },
  },
  {
    id: "xor_x",
    type: "xor-gate",
    mountedAt: { board: "bb", col: 13, row: "e" },
  },
  {
    id: "and_y1",
    type: "and-gate",
    mountedAt: { board: "bb", col: 22, row: "e" },
  },
  {
    id: "and_y2",
    type: "and-gate",
    mountedAt: { board: "bb", col: 31, row: "e" },
  },
  {
    id: "and_y3",
    type: "and-gate",
    mountedAt: { board: "bb", col: 40, row: "e" },
  },
  {
    id: "r_y0",
    type: "resistor",
    ohms: 330,
    mountedAt: { board: "bb", col: 48, row: "c" },
  },
  {
    id: "led_y0",
    type: "led",
    color: "green",
    mountedAt: { board: "bb", col: 50, row: "c" },
  },
  {
    id: "r_y1",
    type: "resistor",
    ohms: 330,
    mountedAt: { board: "bb", col: 52, row: "c" },
  },
  {
    id: "led_y1",
    type: "led",
    color: "yellow",
    mountedAt: { board: "bb", col: 54, row: "c" },
  },
  {
    id: "r_y2",
    type: "resistor",
    ohms: 330,
    mountedAt: { board: "bb", col: 48, row: "h" },
  },
  {
    id: "led_y2",
    type: "led",
    color: "red",
    mountedAt: { board: "bb", col: 50, row: "h" },
  },
  {
    id: "r_y3",
    type: "resistor",
    ohms: 330,
    mountedAt: { board: "bb", col: 52, row: "h" },
  },
  {
    id: "led_y3",
    type: "led",
    color: "blue",
    mountedAt: { board: "bb", col: 54, row: "h" },
  },
  {
    id: "w_a1_nor",
    type: "wire",
    color: "red",
    from: { board: "bb", col: 1, row: "a" },
    to: { board: "bb", col: 4, row: "d" },
  },
  {
    id: "w_a0_nor",
    type: "wire",
    color: "blue",
    from: { board: "bb", col: 2, row: "a" },
    to: { board: "bb", col: 5, row: "d" },
  },
  {
    id: "w_a1_xor",
    type: "wire",
    color: "red",
    from: { board: "bb", col: 1, row: "b" },
    to: { board: "bb", col: 13, row: "d" },
  },
  {
    id: "w_a0_xor",
    type: "wire",
    color: "blue",
    from: { board: "bb", col: 2, row: "b" },
    to: { board: "bb", col: 14, row: "d" },
  },
  {
    id: "w_a0_y1",
    type: "wire",
    color: "blue",
    from: { board: "bb", col: 2, row: "c" },
    to: { board: "bb", col: 22, row: "d" },
  },
  {
    id: "w_x_y1",
    type: "wire",
    color: "white",
    from: { board: "bb", col: 15, row: "d" },
    to: { board: "bb", col: 23, row: "d" },
  },
  {
    id: "w_a1_y2",
    type: "wire",
    color: "red",
    from: { board: "bb", col: 1, row: "c" },
    to: { board: "bb", col: 31, row: "d" },
  },
  {
    id: "w_x_y2",
    type: "wire",
    color: "white",
    from: { board: "bb", col: 15, row: "c" },
    to: { board: "bb", col: 32, row: "d" },
  },
  {
    id: "w_a1_y3",
    type: "wire",
    color: "red",
    from: { board: "bb", col: 1, row: "d" },
    to: { board: "bb", col: 40, row: "d" },
  },
  {
    id: "w_a0_y3",
    type: "wire",
    color: "blue",
    from: { board: "bb", col: 2, row: "d" },
    to: { board: "bb", col: 41, row: "d" },
  },
  {
    id: "w_y0_r",
    type: "wire",
    color: "green",
    from: { board: "bb", col: 6, row: "d" },
    to: { component: "r_y0", end: "p1" },
  },
  {
    id: "w_r_led0",
    type: "wire",
    color: "green",
    from: { component: "r_y0", end: "p2" },
    to: { led: "led_y0", end: "anode" },
  },
  {
    id: "w_y1_r",
    type: "wire",
    color: "yellow",
    from: { board: "bb", col: 24, row: "d" },
    to: { component: "r_y1", end: "p1" },
  },
  {
    id: "w_r_led1",
    type: "wire",
    color: "yellow",
    from: { component: "r_y1", end: "p2" },
    to: { led: "led_y1", end: "anode" },
  },
  {
    id: "w_y2_r",
    type: "wire",
    color: "orange",
    from: { board: "bb", col: 33, row: "d" },
    to: { component: "r_y2", end: "p1" },
  },
  {
    id: "w_r_led2",
    type: "wire",
    color: "orange",
    from: { component: "r_y2", end: "p2" },
    to: { led: "led_y2", end: "anode" },
  },
  {
    id: "w_y3_r",
    type: "wire",
    color: "purple",
    from: { board: "bb", col: 42, row: "d" },
    to: { component: "r_y3", end: "p1" },
  },
  {
    id: "w_r_led3",
    type: "wire",
    color: "purple",
    from: { component: "r_y3", end: "p2" },
    to: { led: "led_y3", end: "anode" },
  },
  {
    id: "w_gnd0",
    type: "wire",
    color: "black",
    from: { led: "led_y0", end: "cathode" },
    to: { board: "bb", rail: "gnd_top", col: 1 },
  },
  {
    id: "w_gnd1",
    type: "wire",
    color: "black",
    from: { led: "led_y1", end: "cathode" },
    to: { board: "bb", rail: "gnd_top", col: 2 },
  },
  {
    id: "w_gnd2",
    type: "wire",
    color: "black",
    from: { led: "led_y2", end: "cathode" },
    to: { board: "bb", rail: "gnd_top", col: 3 },
  },
  {
    id: "w_gnd3",
    type: "wire",
    color: "black",
    from: { led: "led_y3", end: "cathode" },
    to: { board: "bb", rail: "gnd_top", col: 4 },
  },
];
