import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Connect inputs A and B (first half adder)",
  body: "Red wires carry A to XOR1 and AND1; blue wires carry B to XOR1 and AND1. XOR1 now gives A ⊕ B and AND1 gives A · B, which together form the first half adder.",
  show: [
    "bb",
    "xor1",
    "xor2",
    "and1",
    "and2",
    "or1",
    "r_sum",
    "led_sum",
    "r_cout",
    "led_cout",
    "w_a_xor1",
    "w_a_and1",
    "w_b_xor1",
    "w_b_and1",
    "psu",
    "w_rail_link",
    "w_vcc_xor1",
    "w_gnd_xor1",
    "w_vcc_and1",
    "w_gnd_and1",
    "w_vcc_xor2",
    "w_gnd_xor2",
    "w_vcc_and2",
    "w_gnd_and2",
    "w_vcc_or1",
    "w_gnd_or1",
  ],
  highlight: "w_b_and1",
};
