import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Connect Cin and the second half adder",
  body: "Feed the output of XOR1 (A ⊕ B) into XOR2 and AND2 with white wires. Bring the carry-in Cin (orange wires) to XOR2 and AND2. XOR2 gives Sum = A ⊕ B ⊕ Cin and AND2 gives Cin · (A ⊕ B).",
  show: [
    "bb",
    "xor1",
    "xor2",
    "and1",
    "and2",
    "or1",
    "r_sum",
    "led_sum",
    "r_cout",
    "led_cout",
    "w_a_xor1",
    "w_a_and1",
    "w_b_xor1",
    "w_b_and1",
    "w_x1_xor2",
    "w_x1_and2",
    "w_cin_xor2",
    "w_cin_and2",
    "psu",
    "w_rail_link",
    "w_vcc_xor1",
    "w_gnd_xor1",
    "w_vcc_and1",
    "w_gnd_and1",
    "w_vcc_xor2",
    "w_gnd_xor2",
    "w_vcc_and2",
    "w_gnd_and2",
    "w_vcc_or1",
    "w_gnd_or1",
  ],
  highlight: "w_cin_and2",
};
