import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Connect the carry OR gate",
  body: "Connect the outputs of AND1 and AND2 to the two inputs of the OR gate. Its output is the carry-out: Cout = A · B + Cin · (A ⊕ B).",
  show: [
    "bb",
    "xor1",
    "xor2",
    "and1",
    "and2",
    "or1",
    "r_sum",
    "led_sum",
    "r_cout",
    "led_cout",
    "w_a_xor1",
    "w_a_and1",
    "w_b_xor1",
    "w_b_and1",
    "w_x1_xor2",
    "w_x1_and2",
    "w_cin_xor2",
    "w_cin_and2",
    "w_and1_or1",
    "w_and2_or1",
    "psu",
    "w_rail_link",
    "w_vcc_xor1",
    "w_gnd_xor1",
    "w_vcc_and1",
    "w_gnd_and1",
    "w_vcc_xor2",
    "w_gnd_xor2",
    "w_vcc_and2",
    "w_gnd_and2",
    "w_vcc_or1",
    "w_gnd_or1",
  ],
  highlight: "or1",
};
