import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Test: A = 0, B = 1, Cin = 1",
  body: "Set A = 0, B = 1, Cin = 1. A ⊕ B = 1, so AND2 = 1 and the OR gate raises the carry. Expected: Sum = 0 (LED OFF), Cout = 1 (LED ON), since 0 + 1 + 1 = 10 in binary.",
  show: [
    "bb",
    "xor1",
    "xor2",
    "and1",
    "and2",
    "or1",
    "r_sum",
    "led_sum",
    "r_cout",
    "led_cout",
    "w_a_xor1",
    "w_a_and1",
    "w_b_xor1",
    "w_b_and1",
    "w_x1_xor2",
    "w_x1_and2",
    "w_cin_xor2",
    "w_cin_and2",
    "w_and1_or1",
    "w_and2_or1",
    "w_xor2_r",
    "w_r_led_sum",
    "w_or1_r",
    "w_r_led_cout",
    "w_gnd_sum",
    "w_gnd_cout",
    "psu",
    "w_rail_link",
    "w_vcc_xor1",
    "w_gnd_xor1",
    "w_vcc_and1",
    "w_gnd_and1",
    "w_vcc_xor2",
    "w_gnd_xor2",
    "w_vcc_and2",
    "w_gnd_and2",
    "w_vcc_or1",
    "w_gnd_or1",
  ],
  highlight: "led_cout",
  activeInputs: { A: 0, B: 1, Cin: 1 },
  ledBrightness: { led_sum: 0, led_cout: 1 },
};
