import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Test: A = 1, B = 1, Cin = 1",
  body: "Set A = 1, B = 1, Cin = 1. Sum = 1 ⊕ 1 ⊕ 1 = 1 and Cout = 1 · 1 + 1 · 0 = 1. Expected: Sum LED ON, Cout LED ON, since 1 + 1 + 1 = 11 in binary. Now repeat for all eight input combinations and fill the observation table.",
  show: [
    "bb",
    "xor1",
    "xor2",
    "and1",
    "and2",
    "or1",
    "r_sum",
    "led_sum",
    "r_cout",
    "led_cout",
    "w_a_xor1",
    "w_a_and1",
    "w_b_xor1",
    "w_b_and1",
    "w_x1_xor2",
    "w_x1_and2",
    "w_cin_xor2",
    "w_cin_and2",
    "w_and1_or1",
    "w_and2_or1",
    "w_xor2_r",
    "w_r_led_sum",
    "w_or1_r",
    "w_r_led_cout",
    "w_gnd_sum",
    "w_gnd_cout",
    "psu",
    "w_rail_link",
    "w_vcc_xor1",
    "w_gnd_xor1",
    "w_vcc_and1",
    "w_gnd_and1",
    "w_vcc_xor2",
    "w_gnd_xor2",
    "w_vcc_and2",
    "w_gnd_and2",
    "w_vcc_or1",
    "w_gnd_or1",
  ],
  highlight: "led_sum",
  activeInputs: { A: 1, B: 1, Cin: 1 },
  ledBrightness: { led_sum: 1, led_cout: 1 },
};
