import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Connect the borrow-in Bin",
  body: "Orange wires carry Bin to XOR2, XOR3 and XOR4. XOR3 now outputs t = B ⊕ Bin.",
  show: [
    "bb",
    "xor1",
    "xor2",
    "xor3",
    "and1",
    "xor4",
    "r_diff",
    "led_diff",
    "r_bout",
    "led_bout",
    "w_a_xor1",
    "w_b_xor1",
    "w_b_xor3",
    "w_bin_xor2",
    "w_bin_xor3",
    "w_bin_xor4",
    "psu",
    "w_rail_link",
    "w_vcc_xor1",
    "w_gnd_xor1",
    "w_vcc_xor2",
    "w_gnd_xor2",
    "w_vcc_xor3",
    "w_gnd_xor3",
    "w_vcc_and1",
    "w_gnd_and1",
    "w_vcc_xor4",
    "w_gnd_xor4",
  ],
  highlight: "w_bin_xor4",
};
