import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Test: A = 0, B = 1, Bin = 0",
  body: "Set A = 0, B = 1, Bin = 0. You cannot take 1 from 0, so a borrow is generated. Expected: Difference = 1 (LED ON), Borrow = 1 (LED ON).",
  show: [
    "bb",
    "xor1",
    "xor2",
    "xor3",
    "and1",
    "xor4",
    "r_diff",
    "led_diff",
    "r_bout",
    "led_bout",
    "w_a_xor1",
    "w_b_xor1",
    "w_b_xor3",
    "w_bin_xor2",
    "w_bin_xor3",
    "w_bin_xor4",
    "w_x1_xor2",
    "w_x1_and1",
    "w_t_and1",
    "w_g_xor4",
    "w_xor2_r",
    "w_r_led_diff",
    "w_xor4_r",
    "w_r_led_bout",
    "w_gnd_diff",
    "w_gnd_bout",
    "psu",
    "w_rail_link",
    "w_vcc_xor1",
    "w_gnd_xor1",
    "w_vcc_xor2",
    "w_gnd_xor2",
    "w_vcc_xor3",
    "w_gnd_xor3",
    "w_vcc_and1",
    "w_gnd_and1",
    "w_vcc_xor4",
    "w_gnd_xor4",
  ],
  highlight: "led_bout",
  activeInputs: { A: 0, B: 1, Bin: 0 },
  ledBrightness: { led_diff: 1, led_bout: 1 },
};
