import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Wire the three AND gates",
  body: "$Y_1 = A_0 \\cdot X$: connect A0 and the XOR output to **and_y1**. $Y_2 = A_1 \\cdot X$: connect A1 and the XOR output to **and_y2**. $Y_3 = A_1 \\cdot A_0$: connect A1 and A0 directly to **and_y3**.",
  show: [
    "bb",
    "psu",
    "nor_y0",
    "xor_x",
    "and_y1",
    "and_y2",
    "and_y3",
    "r_y0",
    "led_y0",
    "r_y1",
    "led_y1",
    "r_y2",
    "led_y2",
    "r_y3",
    "led_y3",
    "w_a1_nor",
    "w_a0_nor",
    "w_a1_xor",
    "w_a0_xor",
    "w_a0_y1",
    "w_x_y1",
    "w_a1_y2",
    "w_x_y2",
    "w_a1_y3",
    "w_a0_y3",
  ],
  highlight: "and_y1",
};
