import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Connect the gate outputs to the LEDs",
  body: "Connect the output of each gate to its series resistor, and the other end of the resistor to the LED anode.",
  show: [
    "bb",
    "psu",
    "nor_y0",
    "xor_x",
    "and_y1",
    "and_y2",
    "and_y3",
    "r_y0",
    "led_y0",
    "r_y1",
    "led_y1",
    "r_y2",
    "led_y2",
    "r_y3",
    "led_y3",
    "w_a1_nor",
    "w_a0_nor",
    "w_a1_xor",
    "w_a0_xor",
    "w_a0_y1",
    "w_x_y1",
    "w_a1_y2",
    "w_x_y2",
    "w_a1_y3",
    "w_a0_y3",
    "w_y0_r",
    "w_r_led0",
    "w_y1_r",
    "w_r_led1",
    "w_y2_r",
    "w_r_led2",
    "w_y3_r",
    "w_r_led3",
  ],
  highlight: "led_y3",
};
