import { type SceneProcedureStep } from "@/labs/experiments/types";

export const step: SceneProcedureStep = {
  label: "Test: A1 A0 = 11",
  body: "Set $A_1 = 1$ and $A_0 = 1$. Exactly one output is active: $Y_3$ = 1, so only the **blue** LED glows.",
  show: [
    "bb",
    "psu",
    "nor_y0",
    "xor_x",
    "and_y1",
    "and_y2",
    "and_y3",
    "r_y0",
    "led_y0",
    "r_y1",
    "led_y1",
    "r_y2",
    "led_y2",
    "r_y3",
    "led_y3",
    "w_a1_nor",
    "w_a0_nor",
    "w_a1_xor",
    "w_a0_xor",
    "w_a0_y1",
    "w_x_y1",
    "w_a1_y2",
    "w_x_y2",
    "w_a1_y3",
    "w_a0_y3",
    "w_y0_r",
    "w_r_led0",
    "w_y1_r",
    "w_r_led1",
    "w_y2_r",
    "w_r_led2",
    "w_y3_r",
    "w_r_led3",
    "w_gnd0",
    "w_gnd1",
    "w_gnd2",
    "w_gnd3",
  ],
  highlight: "led_y3",
  activeInputs: { A1: 1, A0: 1 },
  supplyVoltage: 5.0,
  ledBrightness: { led_y0: 0.0, led_y1: 0.0, led_y2: 0.0, led_y3: 1.0 },
};
